In [5]:
import torch
import time
import torch.nn as nn
from torch.nn import functional as F
device = 'cuda' if torch.cuda.is_available() else 'cpu'
block_size = 8
batch_size = 4

In [3]:
randint = torch.randint(-100, 100, (6,))
print(randint)

tensor([-66, -38, -82,  46, -50, -11])


In [4]:
tensor = torch.tensor([[0.1, 1.2], [3.5, 9.8], [12.9, 4.1]])
tensor

tensor([[ 0.1000,  1.2000],
        [ 3.5000,  9.8000],
        [12.9000,  4.1000]])

In [5]:
zeros = torch.zeros(4,5)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [6]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [13]:
linspace = torch.linspace(3,10, steps =8)
linspace

tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
logspace = torch.logspace(start =-10, end=10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [16]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
empty_like = torch.empty_like(torch.empty((2,3), dtype=torch.int64))
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [47]:
#time
tic = time.time()
zeros = torch.randint(-100, 100, (100,))
toc = time.time()

print(zeros)
print(f"{(toc-tic)*1000} ms")

tensor([-70, -78,  60, -14,  38,  36,  98, -23,  45,  41,  -3,  84,  28, -93,
         96, -64, -87,  80, -98, -64, -72,   4, -69, -46,  99, -68, -66,  98,
        -80,  61, -60, -52,  74,  57, -15, -75, -87, -16,  91, -43, -62,  65,
        -77, -92, -62, -25, -18,   5,  99,  41,  59, -87,  14, -97, -94,  42,
         77,  52, -21, -71,  64, -17, -24,  66, -77, -98, -50, -27,  29, -61,
        -67, -22,  53,   7,  29,  77, -31,  77, -65, -14,  62,  -7, -99,   7,
        -15,  71,  69, -36, -38, -39, -33, -93,  -3,  57, -87,  66, -70,  74,
         82,  56])
0.3440380096435547 ms


In [36]:
probabilities = torch.tensor([0.1,0.9])
samples = torch.multinomial(probabilities,num_samples=100,replacement=True)
print(samples)

tensor([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        0, 1, 1, 1])


In [37]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [38]:
low_triangular = torch.tril(torch.ones(5,5))
low_triangular

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [39]:
up_triangular = torch.triu(torch.ones(5,5))
up_triangular

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [41]:
inp = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
inp

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [45]:
torch.exp(inp)
#e^(-inf) = 0; e^(0) = 1

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [48]:
inp = torch.zeros(2,3,4)
out = inp.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [49]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
#IMPORTANT
import torch.nn as nn
sample = torch.tensor([10. ,10. ,10.])
linear = nn.Linear(3,3, bias=False)
print(linear(sample))

tensor([ 5.1621, -0.1312, -0.0229], grad_fn=<SqueezeBackward4>)


In [55]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])
SFM_OP = F.softmax(tensor1, dim=0)
print(SFM_OP)
# this is basically converting 
# 	          [e^a /(e^a + e^b + e^c),
# [a,b,c] ->  e^b /(e^a + e^b + e^c),
#             e^c /(e^a + e^b + e^c)]

tensor([0.0900, 0.2447, 0.6652])


In [59]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
#matrix multiplication
print(a @ b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [7]:
x = torch.tensor([-0.05], dtype=torch.float32)
y = F.sigmoid(x)
# sigmoid(x) = 1/(1+e^(-x))
print(y)

tensor([0.4875])
